"""Wrapper around gallery-dl command execution."""
from __future__ import annotations

import logging
import subprocess
from typing import Iterable, List, Optional

logger = logging.getLogger(__name__)


class GalleryDLError(RuntimeError):
    """Exception raised when gallery-dl fails to execute."""


def build_command(
    url: str,
    cookies: Optional[str] = None,
    archive_path: Optional[str] = None,
    rate: Optional[str] = None,
    extra_args: Optional[Iterable[str]] = None,
) -> List[str]:
    """Build a gallery-dl command.

    Parameters
    ----------
    url: str
        Target URL to download from.
    cookies: Optional[str]
        Path to cookies file for authentication. If ``None`` no cookies are used.
    archive_path: Optional[str]
        Path to the download archive file. If ``None`` the archive option is omitted.
    rate: Optional[str]
        Rate limit value passed to ``--rate``. ``None`` to skip.
    extra_args: Optional[Iterable[str]]
        Additional arguments for gallery-dl.

    Returns
    -------
    List[str]
        Fully assembled command list ready for execution.

    Raises
    ------
    ValueError
        If ``url`` is missing.
    """
    if not url:
        raise ValueError("url is required")

    command = ["gallery-dl", url]
    if cookies:
        command.extend(["--cookies", cookies])
    if archive_path:
        command.extend(["--download-archive", archive_path])
    if rate:
        command.extend(["--rate", rate])
    if extra_args:
        command.extend(list(extra_args))
    logger.debug("Built command: %s", command)
    return command


def run(command: Iterable[str]) -> subprocess.CompletedProcess:
    """Run ``gallery-dl`` with the provided command list.

    Parameters
    ----------
    command: Iterable[str]
        Command generated by :func:`build_command`.

    Returns
    -------
    subprocess.CompletedProcess
        Result from ``subprocess.run``.

    Raises
    ------
    GalleryDLError
        If the command execution fails or ``gallery-dl`` is missing.
    """
    try:
        result = subprocess.run(
            list(command),
            check=True,
            capture_output=True,
            text=True,
        )
        logger.info("gallery-dl completed successfully")
        return result
    except FileNotFoundError as exc:
        logger.exception("gallery-dl not found")
        raise GalleryDLError("gallery-dl command not found") from exc
    except subprocess.CalledProcessError as exc:
        logger.exception("gallery-dl execution failed: %s", exc.stderr)
        raise GalleryDLError("gallery-dl execution failed") from exc
